networkAtts = ["HB_LGV_FH_AM","HB_LGV_FH_IP","HB_LGV_FH_PM","HB_LGV_FH_OP","NHB_LGV_FH_AM","NHB_LGV_FH_IP","NHB_LGV_FH_PM","NHB_LGV_FH_OP","HB_LGV_TH_AM_AM","HB_LGV_TH_IP_AM","HB_LGV_TH_PM_AM","HB_LGV_TH_OP_AM","HB_LGV_TH_AM_IP","HB_LGV_TH_IP_IP","HB_LGV_TH_PM_IP","HB_LGV_TH_OP_IP","HB_LGV_TH_AM_PM","HB_LGV_TH_IP_PM","HB_LGV_TH_PM_PM","HB_LGV_TH_OP_PM","HB_LGV_TH_AM_OP","HB_LGV_TH_IP_OP","HB_LGV_TH_PM_OP","HB_LGV_TH_OP_OP"]

actPairAtts = ["RAIL_FH_AM","RAIL_FH_IP","RAIL_FH_PM","RAIL_FH_OP","CAR_TH_AM_AM","CAR_TH_AM_IP","CAR_TH_AM_PM","CAR_TH_AM_OP","CAR_TH_IP_AM","CAR_TH_IP_IP","CAR_TH_IP_PM","CAR_TH_IP_OP","CAR_TH_PM_AM","CAR_TH_PM_IP","CAR_TH_PM_PM","CAR_TH_PM_OP","CAR_TH_OP_AM","CAR_TH_OP_IP","CAR_TH_OP_PM","CAR_TH_OP_OP"]

#"BUS_TH_AM_AM","BUS_TH_AM_IP","BUS_TH_AM_PM","BUS_TH_AM_OP","BUS_TH_IP_AM","BUS_TH_IP_IP","BUS_TH_IP_PM","BUS_TH_IP_OP","BUS_TH_PM_AM","BUS_TH_PM_IP","BUS_TH_PM_PM","BUS_TH_PM_OP","BUS_TH_OP_AM","BUS_TH_OP_IP","BUS_TH_OP_PM","BUS_TH_OP_OP","RAIL_TH_AM_AM","RAIL_TH_AM_IP","RAIL_TH_AM_PM","RAIL_TH_AM_OP","RAIL_TH_IP_AM","RAIL_TH_IP_IP","RAIL_TH_IP_PM","RAIL_TH_IP_OP","RAIL_TH_PM_AM","RAIL_TH_PM_IP","RAIL_TH_PM_PM","RAIL_TH_PM_OP","RAIL_TH_OP_AM","RAIL_TH_OP_IP","RAIL_TH_OP_PM","RAIL_TH_OP_OP","LGV_SPLIT","OCC","CAR_FH_AM","CAR_FH_IP","CAR_FH_PM","CAR_FH_OP","BUS_AUC","BUS_FH_AM","BUS_FH_IP","BUS_FH_PM","BUS_FH_OP","RAIL_AUC",
'''
for att in networkAtts:
    Visum.Net.AddUserDefinedAttribute(att, att, att, 2, 4)
'''

for att in actPairAtts:
    Visum.Net.ActPairs.AddUserDefinedAttribute(att, att, att, 2, 4)
